### ISSUE TITLE
Update to use the latest ibc-proto and ics23 crates

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/ibc-types#3]
Doing this after vendoring checks in https://github.com/penumbra-zone/penumbra/issues/2381 means we can save time by deleting any incompatible code in ibc-types.

**Comment by avahowell** [comment]
This currently isn't possible, because ibc-proto vendors its own copy of the ICS23 protos, and that vendored copy does not have the newest proofspec changes. I think `ibc-proto` will have to cut a new release with updated ics23 protos.

![image](https://user-images.githubusercontent.com/8183920/233752564-eda5a8bd-4d49-4a54-98f7-03cef7a90454.png)

**Comment by romac** [comment]
> I think ibc-proto will have to cut a new release with updated ics23 protos.

I have a pending PR on `ibc-proto` with re-exports the latest `ics23` structs (including the `prehash_key_before_comparison` field) directly instead of vendoring its protos: https://github.com/cosmos/ibc-proto-rs/pull/92

It's currently blocked by this PR on `ics23` (https://github.com/cosmos/ics23/pull/146) but once it's in I can do a release of `ibc-proto` with these changes if they work for you.

**Comment by hdevalence** [comment]
Amazing! That would be great.

**Comment by hdevalence** [comment]
I copied the contents of that branch into a `penumbra` branch on our fork of `ibc-proto`, so that we can move forward: https://github.com/penumbra-zone/ibc-proto-rs/tree/penumbra

**Comment by redshiftzero** [comment]
Done on 0.2.x
